# Generated by Django 5.2.6 on 2025-11-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_bookinglocation_average_cost_bookinghome'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghome',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
